package introspect

import (
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/Clarittyai/devbay/internal/manifest"
)

// Render turns a detected manifest into the file a developer will read.
//
// The header is not decoration. A generated manifest is about to be executed,
// and the two questions a reviewer has are "where did this come from" and
// "what is still wrong" -- so both are answered at the top of the file rather
// than in terminal output that scrolls away. The gaps stay in the file until
// somebody deletes them, which is the point.
func Render(res *Result) ([]byte, error) {
	// Two-space indentation, because yaml.Marshal defaults to four and every
	// hand-written manifest in the ecosystem uses two. A generated file that
	// does not match the house style is a file people mis-edit.
	var out strings.Builder
	enc := yaml.NewEncoder(&out)
	enc.SetIndent(2)
	if err := enc.Encode(res.Manifest); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	body := out.String()

	var b strings.Builder
	b.WriteString("# Generated by `devbay init`.\n#\n")
	b.WriteString("# This file is a proposal, not an answer. Read it before running it:\n")
	b.WriteString("# it describes what will be executed, with the credentials you give it.\n")

	if len(res.Evidence) > 0 {
		b.WriteString("#\n# Where this came from:\n")
		for _, e := range res.Evidence {
			if e.Path != "" {
				fmt.Fprintf(&b, "#   %-16s %s — %s\n", e.Source, e.Path, e.Detail)
			} else {
				fmt.Fprintf(&b, "#   %-16s %s\n", e.Source, e.Detail)
			}
		}
	}

	if len(res.Gaps) > 0 {
		b.WriteString("#\n# STILL TO DECIDE — devbay could not work these out:\n")
		for _, g := range res.Gaps {
			fmt.Fprintf(&b, "#   - %s\n", g)
		}
	}

	b.WriteString("#\n# Note that `egress:` is deliberately absent. devbay never generates a\n")
	b.WriteString("# network allowlist from repository content, because content that could\n")
	b.WriteString("# widen the policy could also be written by someone else. Add it by hand.\n\n")

	b.WriteString(body)
	return []byte(b.String()), nil
}

// Verify reports whether a rendered manifest survives the validator, so
// `devbay init` never writes a file its own tooling would reject.
func Verify(data []byte) (*manifest.Result, error) {
	m, err := manifest.Parse(data)
	if err != nil {
		return nil, err
	}
	return manifest.Validate(m), nil
}
